/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FaqService } from "../faq.service";
import { FaqCreateInput } from "./FaqCreateInput";
import { Faq } from "./Faq";
import { FaqFindManyArgs } from "./FaqFindManyArgs";
import { FaqWhereUniqueInput } from "./FaqWhereUniqueInput";
import { FaqUpdateInput } from "./FaqUpdateInput";

export class FaqControllerBase {
  constructor(protected readonly service: FaqService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Faq })
  async createFaq(@common.Body() data: FaqCreateInput): Promise<Faq> {
    return await this.service.createFaq({
      data: data,
      select: {
        answer: true,
        createdAt: true,
        id: true,
        question: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Faq] })
  @ApiNestedQuery(FaqFindManyArgs)
  async faqs(@common.Req() request: Request): Promise<Faq[]> {
    const args = plainToClass(FaqFindManyArgs, request.query);
    return this.service.faqs({
      ...args,
      select: {
        answer: true,
        createdAt: true,
        id: true,
        question: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Faq })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async faq(@common.Param() params: FaqWhereUniqueInput): Promise<Faq | null> {
    const result = await this.service.faq({
      where: params,
      select: {
        answer: true,
        createdAt: true,
        id: true,
        question: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Faq })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFaq(
    @common.Param() params: FaqWhereUniqueInput,
    @common.Body() data: FaqUpdateInput
  ): Promise<Faq | null> {
    try {
      return await this.service.updateFaq({
        where: params,
        data: data,
        select: {
          answer: true,
          createdAt: true,
          id: true,
          question: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Faq })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFaq(
    @common.Param() params: FaqWhereUniqueInput
  ): Promise<Faq | null> {
    try {
      return await this.service.deleteFaq({
        where: params,
        select: {
          answer: true,
          createdAt: true,
          id: true,
          question: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
