/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Filter } from "./Filter";
import { FilterCountArgs } from "./FilterCountArgs";
import { FilterFindManyArgs } from "./FilterFindManyArgs";
import { FilterFindUniqueArgs } from "./FilterFindUniqueArgs";
import { CreateFilterArgs } from "./CreateFilterArgs";
import { UpdateFilterArgs } from "./UpdateFilterArgs";
import { DeleteFilterArgs } from "./DeleteFilterArgs";
import { FilterService } from "../filter.service";
@graphql.Resolver(() => Filter)
export class FilterResolverBase {
  constructor(protected readonly service: FilterService) {}

  async _filtersMeta(
    @graphql.Args() args: FilterCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Filter])
  async filters(@graphql.Args() args: FilterFindManyArgs): Promise<Filter[]> {
    return this.service.filters(args);
  }

  @graphql.Query(() => Filter, { nullable: true })
  async filter(
    @graphql.Args() args: FilterFindUniqueArgs
  ): Promise<Filter | null> {
    const result = await this.service.filter(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Filter)
  async createFilter(@graphql.Args() args: CreateFilterArgs): Promise<Filter> {
    return await this.service.createFilter({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Filter)
  async updateFilter(
    @graphql.Args() args: UpdateFilterArgs
  ): Promise<Filter | null> {
    try {
      return await this.service.updateFilter({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Filter)
  async deleteFilter(
    @graphql.Args() args: DeleteFilterArgs
  ): Promise<Filter | null> {
    try {
      return await this.service.deleteFilter(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
